{% set name = "rebound" %}
{% set version = "3.6.7" %}
{% set sha256 = "9579fa5d3d3ec3ccd3a1231a796ee2113c61dda695faaf61f8e70fc2103ebf0d" %}

package:
  name: {{ name|lower }}
  version:  {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  skip: true  # [win]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rebound



about:
  home: http://github.com/hannorein/rebound
  license: GPL3
  license_family: GPL
  summary: 'An open-source multi-purpose N-body code'


  description:  |
    REBOUND is an N-body integrator, i.e. a software package that can
    integrate the motion of particles under the influence of gravity.
  doc_url: http://rebound.readthedocs.io/en/latest/
  dev_url: https://github.com/hannorein

extra:
  recipe-maintainers:
    - ACBlock
    - mwcraig
    - hannorein
