{% set name = "rebound" %}
{% set version = "3.6.1" %}
{% set sha256 = "9d3f961dedcaa878a468482f5ec2f6631d6de78cbe16c97c1712396eb0d035c0" %}

package:
  name: {{ name|lower }}
  version:  {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url:  https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  skip: true  # [win]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - rebound



about:
  home: http://github.com/hannorein/rebound
  license: GPL3
  license_family: GPL
  summary: 'An open-source multi-purpose N-body code'


  description:  |
    REBOUND is an N-body integrator, i.e. a software package that can
    integrate the motion of particles under the influence of gravity.
  doc_url: http://rebound.readthedocs.io/en/latest/
  dev_url: https://github.com/hannorein

extra:
  recipe-maintainers:
    - ACBlock
    - mwcraig
    - hannorein
