{% set name = "rebound" %}
{% set version = "3.13.0" %}
{% set sha256 = "6223d9bcbbbbaf3f68ae345cde77f86d3fcd1b8b3d4e4d9475c7a766de5dbd13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rebound

about:
  home: http://github.com/hannorein/rebound
  license: GPL3
  license_family: GPL
  license_file: LICENSE
  summary: An open-source multi-purpose N-body code
  description: |
    REBOUND is an N-body integrator, i.e. a software package that can
    integrate the motion of particles under the influence of gravity.
  doc_url: http://rebound.readthedocs.io/en/latest/
  dev_url: https://github.com/hannorein

extra:
  recipe-maintainers:
    - ACBlock
    - mwcraig
    - hannorein
