travis:
  secure:
    BINSTAR_TOKEN: ixJyd0p0Xjo0ChHGqb3WzgaEmurKEunvW6B5MLvrYL9oZYoIwDPECCTSZZGFpgioAQ9T2DtjUc4/Uj89qbb9taA8feR0sZRxFOM6h5DnRmrvCNuP0kenQeDsF+mfNxtwlMFION2IDavd5MxLAIUrtLQtpPAz0HMHuwDrkbnIF6CcuTHZu5buscBgjBUTH95MEuWwQ61FRWthZsCkKhGtgt+mW/m+QKfhmOFpeW4EJDnD/TKr4gMzw8onXsVcgwNxbHnAMDOju/PiUU/gduAu5lrTJa9hyTfvIcoZNcIUUVXpCOxRmxYxmm/IatBpgDHSbIS267tq3CpQ1ixEJLVS3WQfMOryIjp0iMcWORP0yi962+fTfHOcNyPRXDcv+kBmPD0lllTQhf2BJZcRJkyoB5tz5hVz2YWyjHyWEGYsH32jfGOL1/auuVBdPvNzIQjIMO4l/eJiYzioSAIDNvvGognloI9HselH1WvYbLDycFAkMPuAeZpI4tMw6h88nHiRr6wPriHiMp4kiZoecpp/lbUdIY/3V1Y0p1KRyKEiv+WtB+hlgNro+Pwf7Sba2ZBa4NZuLvcGix8jKCzKxuOcNy6iK/5/apGrbjKIf5xDtM8BAyUTk43ZrcDKXv0ocWgbkCxQlWm3X8me4DSjzj2jor6/2q0Em5xU4xq537asyXE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
